# spring相关配置
spring:
  # 数据源配置
  datasource:
    # 驱动配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接配置(集成 activiti7 时注意设置nullCatalogMeansCurrent=true)
    url: jdbc:mysql://localhost:3306/wiki_user?allowMultiQueries=true&useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=UTF-8
    # url: jdbc:p6spy:mysql://localhost:3306/wiki_user?allowMultiQueries=true&useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=UTF-8
    # 用户名
    username: root
    # 密码
    password: 5211314a
    # sql语句性能分析驱动
  # driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  # Redis相关配置
  redis:
    # 服务器地址
    host: localhost
    # 端口号
    port: 6379
    # 密码（默认空）
    password:
    # 连接超时时间（毫秒）
    timeout: 30000
    # 基于Lettuce的Redis驱动包相关配置
    lettuce:
      # 连接池对象
      pool:
        # 连接池最大连接数（负值表示没有限制，默认值位8）
        max-active: 8
        # 连接池最大阻塞等待时间（负值表示没有限制，默认值为-1ms）
        max-wait: -1ms
        # 连接池中最大空闲连接
        max-idle: 8
        # 连接池中最小空闲连接
        min-idle: 0
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      # 解决 Failed to start bean 'documentationPluginsBootstrapper';
      # nested exception is java.lang.NullPointerException:
      # Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()"
      # because "this.condition" is null
      matching-strategy: ant_path_matcher

# mybatis plus相关配置
mybatis-plus:
  # mybatis plus全局配置
  global-config:
    #禁止打印banner
    banner: false
  # 指定配置
  configuration:
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true
    # 自动映射任意复杂的结果集
    auto-mapping-behavior: full
  # 指定映射文件
  mapper-locations: classpath*:mapper/*.xml

#接口文档系统配置
knife4j:
  # true:启用knife4j增强模式, false:不启用knife4j增强模式
  enable: true
  #是否开启生产环境保护策略,生产环境下禁止访问接口文档系统,生产环境设置为true,开发环境设置为false,
  production: false
  #对Knife4j提供的资源提供BasicHttp校验,保护文档;production配置为true时,basic认证功能不可用
  basic:
    #开启BasicHttp功能
    enable: false
    username: admin
    password: 123321
  #是否开启一个默认的跨域配置,该功能配合自定义Host使用,cors: true
  #  cors: true
debug: true